apiVersion: v1
kind: Service
metadata:
  labels:
    app: admission-webhook-example
  name: admission-webhook-example
  namespace: default
spec:
  ports:
  - name: web
    port: 443
    protocol: TCP
    targetPort: 8081
  selector:
    app: admission-webhook-example
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: admission-webhook-example
  name: admission-webhook-example
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admission-webhook-example
  template:
    metadata:
      labels:
        app: admission-webhook-example
    spec:
      containers:
      - image: domgoer/admission-webhook-example:master-9e7ce91
        args:
        - -cert-dir=/etc/webhook/certs
        - -logtostderr
        - -port=8081
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
        name: admission-webhook-example
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTPS
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ admission-webhook-example-certs }}