# get caBundle:
# kubectl get -n kube-system cm extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n'
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-webhook-example
  labels:
    app: admission-webhook-example
webhooks:
- name: k8s-admission-webhook.mutating.example.app
  clientConfig:
    service:
      name: admission-webhook-example
      namespace: default
      path: /mutate
    caBundle: {{ CA_BUNDLE }}
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  namespaceSelector:
    matchLabels:
      admission-webhook-example: enabled
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-webhook-example
webhooks:
- clientConfig:
    caBundle: {{ CA_BUNDLE }}
    service:
      name: admission-webhook-example
      namespace: default
      path: /validate
  failurePolicy: Fail
  name: k8s-admission-webhook.validating.example.app
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  namespaceSelector:
    matchLabels:
      admission-webhook-example: enabled